sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t balajivenkat/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true balajivenkat/react-test npm test

after_success:
  - docker build -t balajivenkat/multi-client ./client
  - docker build -t balajivenkat/multi-nginx ./nginx
  - docker build -t balajivenkat/multi-server ./server
  - docker build -t balajivenkat/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push balajivenkat/multi-client
  - docker push balajivenkat/multi-nginx
  - docker push balajivenkat/multi-server
  - docker push balajivenkat/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: balu-elb-us-east-1
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY